apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: syntera-postgres-pooler
  namespace: syntera-db
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  cluster:
    name: syntera-postgres
  instances: 2
  type: rw
  pgbouncer:
    poolMode: transaction
    parameters:
      ignore_startup_parameters: extra_float_digits,lock_timeout
  template:
    metadata:
      labels:
        app.kubernetes.io/name: syntera-postgres-pooler
    spec:
      containers:
        - name: pgbouncer
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
