apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bayan-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/Obelion-ai/Bayan.git'
    targetRevision: prod
    path: k8s/overlays/prod
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: bayan-prod
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
