apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/mohamed-abouseada121/prod-cluster.git'
    targetRevision: main
    path: gitops/monitoring
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
