apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: syntera-marketplace-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/opex-sa/syntera-marketplace.git'
    targetRevision: prod
    path: k8s/overlays/prod
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: syntera-marketplace-prod
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/volumeClaimTemplates
    - group: apps
      kind: Deployment
      name: syntera-backend
      jsonPointers:
        - /spec/replicas
